# Configuration values defined here override any values defined in deployment.yml
---
meta:
  # inherits: cluster
  components:
    provider: aws/instance
    image: development

platform:
  nginx_host_port: 3000
  environment:
    request_logging:
      enabled: no
    system_logging:
      enabled: no
  basic_services:
    fluentd:
      enabled: no
    localstack:
    nginx:
    postgres:
    redis:
    wait:

services:
  cognito:
    profiles: ['server']
  comm:
    profiles: ['server']
  iam:
    profiles: ['server']

provider:
  region: us-east-1
  instance:
    type: m6.large

infra:
  dns:
    domain: rails-on-services.org
    subdomain: ros
