version: '3'
services:
  wait:
    image: waisbrot/wait
    depends_on:
      - db
    environment:
      TARGETS: 'db:5432'
  db:
    image: mdillon/postgis:9.6
    ports:
      - "5432" # - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
  nginx:
    image: nginx
    ports:
      - "${NGINX_HOST_PORT:-3000}:80" # expose port 3000 on host and pass to port 80 of the nginx container
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./containers/nginx/services.conf:/etc/nginx/conf.d/services/project.conf
